### ISSUE TITLE
gui selection does not respond

### ISSUE THREAD

**Issue by KEVIN910919** [EnvyWare/EnvyGTS#11]
[05:33:17] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
 java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_291]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_291]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:926) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:865) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:737) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_291]
Caused by: java.lang.NullPointerException
        at com.envyful.reforged.gts.forge.ui.ViewTradesUI.openUI(ViewTradesUI.java:43) ~[ViewTradesUI.class:?]
        at com.envyful.reforged.gts.forge.ui.ViewTradesUI.openUI(ViewTradesUI.java:24) ~[ViewTradesUI.class:?]
        at com.envyful.reforged.gts.forge.ui.MainUI.lambda$open$3(MainUI.java:63) ~[MainUI.class:?]
        at com.envyful.reforged.gts.forge.shade.envy.api.forge.gui.item.ForgeSimpleDisplayable.onClick(ForgeSimpleDisplayable.java:31) ~[ForgeSimpleDisplayable.class:?]
        at com.envyful.reforged.gts.forge.shade.envy.api.forge.gui.ForgeGui$ForgeGuiContainer.func_184996_a(ForgeGui.java:278) ~[ForgeGui$ForgeGuiContainer.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:2148) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38) ~[lf.class:?]
        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12) ~[lf.class:?]
        at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:14) ~[hv.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_291]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_291]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more
       

Minecraft version: 1.12.2 in Magma 761933c-STABLE
ReforgedGTS-Forge version: 2.0.7-1.12.2
Server software: Windows10

**Comment by danorris709** [comment]
Fixed in 1.16.5
