### ISSUE TITLE
1.20.2 crash on startup

### ISSUE THREAD

**Issue by thewickening** [EnvyWare/EnvyGTS#41]
So kind of a weird one, if you have a pre-existing config from 1.16, it loads fine, but when you get in-game nothing works with gts.

If you don't have a config, crashes on startup.
https://pastebin.com/1d5PkXV3

**Comment by danorris709** [comment]
So the startup crash from the new config is because the database isn't setup. But I think the config changed between the two versions potentially?

**Comment by thewickening** [comment]
> So the startup crash from the new config is because the database isn't setup. But I think the config changed between the two versions potentially?

I think you are correct, regenned and synced to mysql, no more crash on startup. However, this error appears upon join and same you do not have permission to use this command "even though I do"

`[09:33:32] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: A wild TheWickening appeared!
[09:33:32] [envyware_concurrency_1/ERROR] [EnvyGTS]: Error when loading attribute data for com.envyful.gts.forge.player.GTSAttribute
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "com.envyful.gts.forge.shade.envy.api.forge.player.ForgeEnvyPlayer.getUniqueId()" because "this.parent" is null
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) [?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "com.envyful.gts.forge.shade.envy.api.forge.player.ForgeEnvyPlayer.getUniqueId()" because "this.parent" is null
	at com.envyful.gts.forge.player.GTSAttribute.load(GTSAttribute.java:83) ~[EnvyGTS-Forge-4.5.7-1.20.2.jar%23166!/:?]
	at com.envyful.gts.forge.shade.envy.api.player.attribute.PlayerAttribute.load(PlayerAttribute.java:66) ~[EnvyGTS-Forge-4.5.7-1.20.2.jar%23166!/:?]
	at com.envyful.gts.forge.shade.envy.api.player.attribute.PlayerAttribute.load(PlayerAttribute.java:28) ~[EnvyGTS-Forge-4.5.7-1.20.2.jar%23166!/:?]
	at com.envyful.gts.forge.shade.envy.api.player.save.impl.EmptySaveManager.lambda$loadAttribute$0(EmptySaveManager.java:46) ~[EnvyGTS-Forge-4.5.7-1.20.2.jar%23166!/:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 6 more`

**Comment by danorris709** [comment]
Does this happen with the latest version?
